const sectorOptions = [
  { value: "", label: "All Sectors" },
  { value: "AGRICULTURE_AND_FARMING", label: "Agriculture and Farming" },
  { value: "CONSTRUCTION_AND_INFRASTRUCTURE", label: "Construction and Infrastructure" },
  { value: "CONSUMER_AND_RETAIL", label: "Consumer and Retail" },
  { value: "DEFENSE_AND_SECURITY", label: "Defense and Security" },
  { value: "DESIGN_AND_CREATIVE", label: "Design and Creative" },
  { value: "EDUCATION", label: "Education" },
  { value: "ENERGY_AND_ENVIRONMENT", label: "Energy and Environment" },
  { value: "EVENTS_AND_HOSPITALITY", label: "Events and Hospitality" },
  { value: "FINANCE_AND_INSURANCE", label: "Finance and Insurance" },
  { value: "HEALTH_AND_WELLNESS", label: "Health and Wellness" },
  { value: "INDUSTRY_AND_MANUFACTURING", label: "Industry and Manufacturing" },
  { value: "INFORMATION_TECHNOLOGY_AND_SERVICES", label: "IT and Services" },
  { value: "LOGISTICS_AND_TRANSPORTATION", label: "Logistics and Transportation" },
  { value: "MEDIA_AND_ENTERTAINMENT", label: "Media and Entertainment" },
  { value: "NON_PROFITS_AND_PHILANTHROPY", label: "Non-profits and Philanthropy" },
  { value: "OTHER_MATERIALS_AND_PRODUCTION", label: "Other Materials and Production" },
  { value: "PHARMACEUTICALS", label: "Pharmaceuticals" },
  { value: "PROFESSIONAL_SERVICES_AND_CONSULTING", label: "Professional Services and Consulting" },
  { value: "PUBLIC_SECTOR_AND_GOVERNMENT", label: "Public Sector and Government" },
  { value: "REAL_ESTATE", label: "Real Estate" },
  { value: "TECHNOLOGY_AND_TELECOMMUNICATIONS", label: "Technology and Telecommunications" },
];